### ISSUE TITLE
Login Weirdness

### ISSUE THREAD

**Issue by SDRichards** [osu-cs290-sp19/the-gnome-depot#16]
The password field is getting messed up because some CSS is getting injected into it. I'm pretty sure the culprit is Lastpass. It's likely that the grader has lastpass, so probs needs to be fixed. 
I'm not quite sure what's going on though.

**Comment by lyellread** [comment]
Replaced with a different setup in https://github.com/osu-cs290-sp19/the-gnome-depot/tree/login-work. Marking as fixed.
