### ISSUE TITLE
Gnomes as search button and guarding the other side of the search bar...

### ISSUE THREAD

**Issue by lyellread** [osu-cs290-sp19/the-gnome-depot#35]
<standard gnome> [SEARCH BAR] <gnome with magnifying glass>

I will be committing the magnifying glass gnome soon. They should both be facing the search bar. Clicking on the magnifing glass gnome (right hand side) should initiate search.

**Comment by SDRichards** [comment]
Can't really see the magnifying glass, since it's so small. But that's fine

**Comment by lyellread** [comment]
Reopening till the gnomes are satisfying to OCD-ness. @SDRichards

**Comment by SDRichards** [comment]
Master is on fire(in good way)
