### ISSUE TITLE
Cannot Push, Set Settings, Add Collaborators ...

### ISSUE THREAD

**Issue by lyellread** [osu-cs290-sp19/the-gnome-depot#4]
This is kinda an oof. I would love to get this fixed @robwhess . The contributors are myself, @lyellread , @bolym, @sdrichards.

This is also preventing access to settings, and to projects tab, and to add people.

**Comment by robwhess** [comment]
Not sure what happened there.  I invited all of you to the team @osu-cs290-sp19/the-gnome-depot-team (which you were already a member of, @lyellread) and gave that team admin permissions on this repo.  Let me know if you still have trouble.
